[project]
name = "Auralium"
description = "A music player"
authors = [
    { name="Namester (Nmstr)", email="publicNamester@gmail.com" }
]
dependencies = [
    "pygame",
]

[tool.ruff]
lint.select = ["E4", "E7", "E9", "F", "N8"]
